### ISSUE TITLE
Can you give some test or demo code 

### ISSUE THREAD

**Issue by HaomingJu** [DLR-TS/xodr#5]

**Comment by tlobig** [comment]
Hi,
this repository has only the header to help parse a xodr file.

It's used in ADORe though, which is also maintained by us:

https://github.com/eclipse/adore

Take a look at

https://github.com/eclipse/adore/blob/master/libadore/adore/if_xodr/include/adore/if_xodr/xodr2borderbased.h

maybe it helps to get an idea on how to use the header file from this repo.

**Comment by HaomingJu** [comment]
THANK YOU
